version: '3.8'

services:
  app-server:
    container_name: app-server
    build: ./server
    env_file: .env
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
    environment:
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - VERISOUL_API_KEY=$VERISOUL_API_KEY # reach out to hello@verisoul.xyz for an api key
    networks:
      - app

  app-client:
    container_name: app-client
    depends_on:
      - app-server
    build:
      context: ./client
      args:
        - NPM_TOKEN=$NPM_TOKEN # reach out to hello@verisoul.xyz for a npm token
    env_file: .env
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    networks:
      - app

networks:
  app: